name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Set up Goose for DB Migrations
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Build Go app
        run: ./scripts/buildprod.sh

      - name: Database Migrations
        run: ./scripts/migrateup.sh

      - name: GCS Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build, Tag and Push image to Google Artifact Registry
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/notely-421816/notely-ar-repo/notely:latest .

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-421816/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-421816 --max-instances=4
